# This is a basic workflow to help you get started with Actions

name: WallOfZenCI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Log the repo name
        run: |
          echo Repo name: $GITHUB_REPOSITORY
      - uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ntrogh/devopsdaysams-actions/wallofzen
          tags: latest,${{ github.sha }}
          tag_with_ref: true

  deploy:
      runs-on: ubuntu-latest
      needs: build

      steps:
        - uses: azure/login@v1.1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        - uses: 'azure/aci-deploy@v1'
          with:
            resource-group: devopsdaysams
            dns-name-label: wallofzen1
            image: docker.pkg.github.com/ntrogh/devopsdaysams-actions/wallofzen:${{ github.sha }}
            registry-login-server: docker.pkg.github.com
            registry-username: ${{ github.actor }}
            registry-password: ${{ secrets.GITHUB_TOKEN }}
            name: ntwallofzen1
            location: 'west europe'
          environment-variables: BASE_URL=https://devopsdaysams.azurewebsites.net/api/AddToWall
